corp/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import RedirectView
from index.views import home, species
from user.views import Dashboard
from django.urls import re_path

admin.autodiscover()

urlpatterns = [

    path("ads.txt", RedirectView.as_view(
        url=staticfiles_storage.url("ads.txt")),),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('species/', species),
    path('user/', include('user.urls')),
    path('ckeditor', include(
        'ckeditor_uploader.urls')),
    path('forestry/', include(('forestry.urls',
                               'forestry'), namespace='forestry')),
    path('accounts/', include('allauth.urls')),
    path(
        'store/', include(('store.urls', 'store'), namespace='store')),
    path('dashboard/', Dashboard.as_view(),
         name='profile'),
    path('hitcount/', include(('hitcount.urls',
                               'hitcount'), namespace='hitcount')),
    path('dashboad/', include(('dashboard.urls',
                               'dashboard'), namespace='dashboard')),

)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('remove_task/<int:pk>/<action>/',
         views.remove_task, name='remove_task'),
    path('remove_worker/<pk>/', views.delete_worker, name='remove-worker'),
    path('task/<pk>/', views.complete_task, name='complete_task'),
]

store/urls.py
from django.urls import path

from user.views import edit_product

from .views import (AddCouponView, CheckoutView, HomeView, OrderSummaryView,
                    PaymentView, RequestRefundView, SeedProductDetailView,
                    add_to_cart, cancel_order, delete_product, download_pdf,
                    generate_card, order_detail, order_received_view,
                    remove_from_cart, remove_single_item_from_cart,
                    request_refund_view, update_item_cart_quantity)

app_name = 'store'

urlpatterns = [
    # path('', TreeSeedListView.as_view(), name='list_seeds'),
    # path('<slug>', TreeSeedDetailView.as_view(), name='detail_seed'),
    path('', HomeView.as_view(), name='store'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', SeedProductDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('generate-card/<slug>', generate_card, name='generate-card'),
    path('download/pdf/<slug>/', download_pdf, name='download-pdf'),
    path('edit-product/<pk>/', edit_product, name='edit_product'),
    path('delete-product/<pk>', delete_product, name='delete_product'),
    path('order-detail/<pk>/', order_detail, name='order-detail'),
    path('cancel-order/<pk>/', cancel_order, name='cancel-order'),
    path('received-order/<pk>/', order_received_view, name='received-order'),
    path('refund/<pk>/', request_refund_view, name='request-refund'),
    path('update/cart/item/quantity/', update_item_cart_quantity,
         name="update-item-cart-quantity")
]

user/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .utils import validate_email

urlpatterns = [
    path('ajax/validate_email', validate_email, name='validate_email'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('admin/', views.AdminView.as_view(), name='admin_view'),
    path('order/', views.OrderView.as_view(), name='orders'),
    path('product/', views.ProductView.as_view(), name='product'),
    path('notifications/', views.Notification.as_view(), name='notification'),
    path('profile/', views.UpdateProfileView.as_view(), name='update-profile'),
    path('api/data/', views.get_data, name="get_data"),
    path('api/chart/data', views.ChartData.as_view(), name="chart-data"),
    path('api/big-chart-data/', views.big_chart_data, name='big-chart-data'),
    path('nursery/', views.NurseryView.as_view(), name='nursery-view'),
    path('test/', views.test),
    path('user/delete/<email>/', views.delete_user, name="delete-account")
]

dashboard/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class NurseryManager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=50, blank=False, null=True)
    telephone = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return '%s - %s' % (self.user.get_full_name(), self.location)


class Species(models.Model):
    scientific_name = models.CharField(
        blank=False, unique=True, max_length=255)
    seeds_kg = models.IntegerField(blank=True)


class Nursery(models.Model):
    # Choices

    # DATABASE

    manager = models.ForeignKey(NurseryManager, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=False)
    location = models.CharField(max_length=100, blank=True, null=True)
    species = models.ManyToManyField(Species)


class SowingBed(models.Model):
    nursery = models.ForeignKey(Nursery, on_delete=models.CASCADE)
    size = models.CharField(max_length=255, blank=True, null=True)
    specie = models.ManyToManyField(Species)
    sowing_date = models.DateTimeField(auto_now=False, blank=True, null=True)


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    action = models.CharField(max_length=255, blank=False, null=False)
    date_completed = models.DateTimeField(
        blank=True, null=True, auto_now_add=False)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name

    def complete_url(self):
        return reverse('dashboard:complete_task', kwargs={'pk': self.id})


class Workers(models.Model):
    # CHOICES
    # DATABASE
    account_number = models.CharField(max_length=20, blank=True)
    full_name = models.CharField(max_length=255, )
    job = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    salary = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.full_name

    def pay_url(self):
        return reverse('dashboard:pay_worker', kwargs={'pk': self.id})

    def delete_url(self):
        return reverse('dashboard:remove-worker', kwargs={'pk': self.id})

user/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models
from django.db.models.signals import post_save
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def create_user(
            self, email, first_name, last_name, password=None,
            commit=True):
        """
        Creates and saves a User with the given email, first name, last name
        and password.
        """
        if not email:
            raise ValueError(_('User must have an email address'))
        if not first_name:
            raise ValueError(_('User must have a first name'))
        if not last_name:
            raise ValueError(_('User must have a last name'))

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        if commit:
            user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        """
        Creates and saves a superuser with the given email, first name,
        last name and password.
        """
        user = self.create_user(
            email,
            password=password,
            first_name=first_name,
            last_name=last_name,
            commit=False,
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name=_('email address'), max_length=255, unique=True
    )
    # password field supplied by AbstractBaseUser
    # last_login field supplied by AbstractBaseUser
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'
        ),
    )
    # is_superuser field provided by PermissionsMixin
    # groups field provided by PermissionsMixin
    # user_permissions field provided by PermissionsMixin

    date_joined = models.DateTimeField(
        _('date joined'), default=timezone.now
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    class Meta:
        db_table = 'auth_user'
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def __str__(self):
        return '{} <{}>'.format(self.get_full_name(), self.email)

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True


class UserProfile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    location = models.CharField(max_length=200, blank=True)
    image = models.ImageField(upload_to='profile', blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)
    stripe_customer_id = models.CharField(blank=True, max_length=50, null=True)
    biography = models.TextField(blank=True, null=True)
    is_manager = models.BooleanField(default=False)
    is_author = models.BooleanField(default=False)

    def __str__(self):
        return '{}-Profile'.format(self.user.first_name)


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=get_user_model())

dashboard/forms.py
from django import forms
from django.forms import ModelForm

from .models import Nursery, Task, Workers


class AddTaskForm(ModelForm):
    class Meta:
        model = Task
        exclude = ['user']


class NurseryForm(ModelForm):
    class Meta:
        model = Nursery
        fields = '__all__'


class AddWorker(ModelForm):
    class Meta:
        model = Workers
        fields = '__all__'

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from store.models import Address
from dashboard.models import NurseryManager
from .models import User, UserProfile


class CreateUserForm(UserCreationForm):
    """
    New User Form. Requires password confirmation.
    """
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Confirm password', widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

    def signup(self, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']
        required = ['first_name', 'last_name']


class UpdateAddressForm(forms.ModelForm):
    country = CountryField(blank_label='(select country)').formfield(
        required=False, widget=CountrySelectWidget(attrs={
            'class': 'form-control custom-select my-1 width-90'}))

    class Meta:
        model = Address
        fields = ['city', 'district', 'street_address', 'country']


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image', 'biography']
        widgets = {
            'biography': forms.Textarea(attrs={'rows': 3, 'cols': 60}),
        }


class NurseryManagerRegistration(forms.ModelForm):
    class Meta:
        model = NurseryManager
        exclude = ['user']

dashboard/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.db.models.functions import Trunc
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from store.models import SeedProduct

from .models import Task, Workers

User = get_user_model()


@login_required
def remove_task(request, pk, action):
    task = get_object_or_404(Task, pk=pk)
    task_qs = Task.objects.filter(user=request.user, status=False)

    if task_qs.exists():
        task = task_qs[0]
        ref = task.id
        if action == "delete":
            task.delete()
            messages.info(request, 'Task deleted')
            return JsonResponse({'message': "Task deleted", "id": ref})
        elif action == "completed":
            task.status = True
            task.date_completed = timezone.now()
            task.save()
            return JsonResponse({'message': "Task has been completed", "id": ref})
        else:
            return render(request, "dashboard/includes/forms.html")

    else:
        return JsonResponse({'message': "You don't have a task"})


@login_required
def complete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task_qs = Task.objects.filter(user=request.user, status=False)

    if task_qs.exists():
        task = task_qs[0]
        task.status = True
        task.date_completed = datetime.now()
        task.save()
        messages.info(request, 'Task completed')
        return redirect('profile')
    else:
        messages.info(request, "Not found")
        return redirect('profile')


@login_required
def delete_worker(request, pk):
    worker = Workers.objects.get(id=pk)
    name = worker.full_name

    worker.delete()
    messages.warning(request, '{} - Has been removed'.format(name))
    return redirect('notification')

templates/dashboard/pages/orders.html
{% extends 'dashboard/layouts/base.html' %}
{% load humanize %}
{% load static %}

{% block title %} Orders {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="panel-header panel-header-sm">
</div>
<div class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title"> My Orders</h4>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <thead class=" text-primary">
                <th>
                  Ref Code
                </th>
                <th>
                  Start Date
                </th>
                <th>
                  Ordered
                </th>
                <th class="text-right">
                  Total Amount
                </th>
              </thead>
              <tbody>

                {% for order in orders %}
                <tr>
                  <td>
                    <a id="order-detail" data-toggle="modal" data-target="#orderDetail"
                      data-url="{{order.order_detail_url}}" href="" class="order-detail">{{order.ref_code}}</a>
                  </td>
                  <td>
                    {{order.start_date|date}}
                  </td>
                  <td>
                    {{order.ordered}}
                  </td>
                  <td class="text-right">
                    <strong>{{order.get_total|intcomma}}&nbsp;Rwf</strong>
                  </td>

                  {% empty %}
                  <td colspan="3" class="text-center">No order yet</td>
                  <td colspan="2" class="text-center"><a href="{% url 'store:store' %}" class="btn btn-primary">Go
                      shopping</a> </td>

                </tr>

                {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- ORDER DETAIL -->
<div class="modal fade" id="orderDetail" tabindex="-1" role="dialog" aria-labelledby="order_detail" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Order Detail</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-sm-4">
            <p class="order_id_p">Order_Id: </p>
          </div>
          <div class="col-sm-8 font-weight-bold">
            <p class="order_detail_id">None</p>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <p class="order_total_p">Order Total(Rwf): </p>
          </div>
          <div class="col-sm-8 font-weight-bold">
            <p class="order_total_amount">None</p>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <p class="total_items">Total Items: </p>
          </div>
          <div class="col-sm-8 font-weight-bold">
            <p class="total_items_count">1</p>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <p class="delivered">Being Delivered: </p>
          </div>
          <div class="col-sm-8 font-weight-bold text-info">
            <p class="delivered_status">False</p>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4">
            <p class="received">Order Received:</p>
          </div>
          <div class="col-sm-8 font-weight-bold text-info">
            <p class="received_status">False</p>
          </div>
        </div>
      </div>
      <hr>
      <div class="button-container m-auto">
          <a href="{% url 'store:checkout' %}" class="btn btn-primary">Checkout</a>
          <a href="" class="btn btn-danger" id="cancel_order">Cancel Order</a>
        
      </div>
    </div>
  </div>
</div>
<!-- // ORDER DETAIL -->

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script src="{% static 'js/order.js' %}"></script>
{% endblock javascripts %}

templates/dashboard/pages/product.html
{% extends 'dashboard/layouts/base.html' %}
{% load humanize %}
{% load widget_tweaks %}
{% load static %}

{% block title %} Products {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<link rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.17/css/bootstrap-select.min.css"
  integrity="sha256-VMPhaMmJn7coDSbzwqB0jflvb+CDnoAlfStC5RogOQo=" crossorigin="anonymous" />
{% endblock stylesheets %}

{% block content %}

<!-- End Navbar -->
<div class="panel-header panel-header-sm">
</div>

<div class="content">

  <!-- All PRODUCTS -->
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title text-center"> All Products</h4>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table overflow-auto">
              <thead class=" text-primary">
                <th>
                  No
                </th>
                <th>
                  Name
                </th>
                <th>
                  Available
                </th>
                <th class="text-right">
                  Price
                </th>
                <th class="text-right">
                  Action
                </th>
              </thead>
              <tbody>

                {% for product in products %}
                <tr>
                  <td>
                    {{forloop.counter}}
                  </td>
                  <td>
                    {{product.scientific_name}}
                  </td>
                  <td>
                    {{ product.available}}

                  </td>
                  <td class="text-right">

                    {% if product.discount_price %}
                    <del>{{product.price|intcomma}}</del> &nbsp;{{product.discount_price|intcomma}}&nbsp;Rwf
                    {% else %}

                    {{product.price|intcomma}}&nbsp;Rwf
                    {% endif %}
                  </td>

                  <td class="text-right">
                    <a href="{{ product.edit_url}}">Edit</a> or <a href="{{ product.delete_url}}" class="delete_product"
                      data-product="{{ product.id}}">Delete</a>


                  </td>
                  {% empty %}
                  <td colspan="3" class="text-center">No Product</td>
                  <td colspan="2" class="text-center"><a href="{% url 'store:store' %}" class="btn btn-primary">Add New
                      Product</a> </td>

                </tr>

                {% endfor %}

              </tbody>
            </table>
          </div>
          <button class="btn btn-primary" id="add-product" data-toggle="modal" data-target="#addProduct">Add
            Product</button>
        </div>
      </div>
    </div>
  </div>
  <!-- // ALL PRODUCTS -->

</div>


<!-- FORMS -->
<!-- FORMS -->
<div class="modal fade" id="addProduct" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Product</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" class="md-form" action="." enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-6 pr-1">
              <div class="form-group">
                <label for="">{{form.scientific_name.label}}</label>
                {% render_field form.scientific_name class="form-control"%}
              </div>
            </div>
            <div class="col-md-6 pl-1">
              <div class="form-group">
                <label for="">{{form.common_name.label}}</label>
                {% render_field form.common_name class="form-control"%}

              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 pr-1">
              <div class="form-group">
                <label for="">{{form.price.label}}</label>
                {% render_field form.price class="form-control"%}
              </div>
            </div>
            <div class="col-md-4 px-1">
              <div class="form-group">
                <label for="">{{form.discount_price.label}}</label>
                {% render_field form.discount_price class="form-control"%}
              </div>
            </div>
            <div class="col-md-4 pl-1">
              <div class="form-group">
                <label for="">{{ form.category.label}}</label>
                {% render_field form.category class="custom-select"%}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 pr-1">
              <div class="form-group">
                <label for="">{{ form.seeds_kg.label}}</label>
                {% render_field form.seeds_kg class="form-control"%}
              </div>
            </div>
            <div class="col-md-4 px-1">
              <div class="form-group">
                <label for="">{{form.germination_rate.label}}</label>
                {% render_field form.germination_rate class="form-control"%}
              </div>
            </div>
            <div class="col-md-4 pl-1">
              <div class="form-group">
                <label for="">{{form.seed_source.label}}</label>
                {% render_field form.seed_source class="form-control"%}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 pr-1">
              <div class="form-group">
                <label for="">{{form.seed_type.label}}</label>
                {% render_field form.seed_type class="custom-select"%}
              </div>
            </div>
            <div class="col-md-6 pl-1">
              <div class="form-group">
                <label for="">{{form.pre_treatment.label}}</label>
                {% render_field form.pre_treatment class="custom-select"%}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 pr-1">
              <div class="custom-file">
                <input type="file" class="custom-file-input" name="image1" id="id_image1">
                <label for="id_image1" class="custom-file-label" id="image1_label">Tree Image</label>
              </div>

            </div>
            <div class="col-md-6 pl-1">
              <div class="custom-file">
                <input type="file" class="custom-file-input" name="image2" id="id_image2">
                <label for="id_image2" class="custom-file-label" id="image2_label">Seed Image</label>
              </div>

            </div>
          </div>

          <div class="row">
            <div class="col-md-6 pr-1">
              <div class="form-group">
                <label for="">{{ form.plantation_districts.label}}</label>
                {{form.plantation_districts}}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="">OverView</label>
                {{ form.short_note}}
              </div>
            </div>
          </div>
          <!-- CHECK BOXES -->
          <div class="row">
            <div class="col-md-6">
              <div class="custom-control custom-checkbox form-check-inline">
                <input type="checkbox" name="available" id="available" class="custom-control-input">
                <label for="available" class="custom-control-label">Available</label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="custom-control custom-checkbox form-check-inline">
                <input type="checkbox" name="recommended" id="recommended" class="custom-control-input">
                <label for="recommended" class="custom-control-label">Recommended</label>
              </div>
            </div>
          </div>

          <input type="submit" value="Add Product" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</div>



{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.17/js/bootstrap-select.min.js"
  integrity="sha256-QOE02Glo1C1gHzP96JOaxyIMt4XSFv/exZaYLY4dwO0=" crossorigin="anonymous"></script>
<script src="{% static 'js/dashboard.js' %}"></script>

<script>
  $(document).ready(function () {
    // Javascript method's body can be found in assets/js/demos.js
    demo.initDashboardPageCharts();
  });

</script>
<script>

  {% if form.errors %}
  $("#addProduct").modal('show')
  {% endif %}

</script>

{% endblock javascripts %}