corp/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import RedirectView
from index.views import home, species
from user.views import Dashboard
from django.urls import re_path

admin.autodiscover()

urlpatterns = [

    path("ads.txt", RedirectView.as_view(
        url=staticfiles_storage.url("ads.txt")),),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('species/', species),
    path('user/', include('user.urls')),
    path('ckeditor', include(
        'ckeditor_uploader.urls')),
    path('forestry/', include(('forestry.urls',
                               'forestry'), namespace='forestry')),
    path('accounts/', include('allauth.urls')),
    path(
        'store/', include(('store.urls', 'store'), namespace='store')),
    path('dashboard/', Dashboard.as_view(),
         name='profile'),
    path('hitcount/', include(('hitcount.urls',
                               'hitcount'), namespace='hitcount')),
    path('dashboad/', include(('dashboard.urls',
                               'dashboard'), namespace='dashboard')),

)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from user.views import edit_product

from .views import (AddCouponView, CheckoutView, HomeView, OrderSummaryView,
                    PaymentView, RequestRefundView, SeedProductDetailView,
                    add_to_cart, cancel_order, delete_product, download_pdf,
                    generate_card, order_detail, order_received_view,
                    remove_from_cart, remove_single_item_from_cart,
                    request_refund_view, update_item_cart_quantity)

app_name = 'store'

urlpatterns = [
    # path('', TreeSeedListView.as_view(), name='list_seeds'),
    # path('<slug>', TreeSeedDetailView.as_view(), name='detail_seed'),
    path('', HomeView.as_view(), name='store'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', SeedProductDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('generate-card/<slug>', generate_card, name='generate-card'),
    path('download/pdf/<slug>/', download_pdf, name='download-pdf'),
    path('edit-product/<pk>/', edit_product, name='edit_product'),
    path('delete-product/<pk>', delete_product, name='delete_product'),
    path('order-detail/<pk>/', order_detail, name='order-detail'),
    path('cancel-order/<pk>/', cancel_order, name='cancel-order'),
    path('received-order/<pk>/', order_received_view, name='received-order'),
    path('refund/<pk>/', request_refund_view, name='request-refund'),
    path('update/cart/item/quantity/', update_item_cart_quantity,
         name="update-item-cart-quantity")
]

store/models.py
from autoslug.fields import AutoSlugField
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField
from forestry.models import BlogPost
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

from .utils import photo_path

User = get_user_model()


def get_product_map(product):
    districts = []
    for district in product.districts.all():
        districts.append(district.name)


class District(models.Model):
    # CHOICES
    ecological_zones = (('HIGH', 'Highland'),
                        ('LOW', 'Lowlands'), ('Mid', 'Midlands'))

    # DATABASE FIELDS
    name = models.CharField(max_length=255, unique=True)
    ecelogical_zone = models.CharField(
        max_length=255, choices=ecological_zones, default='Mid')

    class Meta:
        verbose_name = 'district'
        verbose_name_plural = 'districts'
        ordering = ['name']

    # Functions
    def __str__(self):
        return self.name


class TypesOfSeed(models.Model):
    # CHOICES
    types = (('ORT', 'Orthodox'), ('RECAL', 'Recalcitrant'),
             ('SUB-OR', 'Sub-Orthodox'))
    storage = (
        ('RT', 'Room temperature'),
        ('CRT', 'Cold room temperature')
    )

    # DATABASE FIELDS
    name = models.CharField(max_length=100, choices=types)
    storage_type = models.CharField(
        _('storage type'), max_length=500, choices=storage)
    max_years = models.IntegerField(_('Max storage years'), blank=True)
    min_years = models.IntegerField(_('Min storage years'), blank=True)
    max_moisture = models.IntegerField(
        blank=True, verbose_name='Max Storage Moisture')
    min_moisture = models.IntegerField(
        blank=True, verbose_name='Min Storage Moisture')
    overview = RichTextUploadingField(_('overview'), blank=True, null=True)

    # FUNCTIONS

    class Meta:
        verbose_name = 'Seed Type'
        verbose_name_plural = 'Seed Types'

    def __str__(self):
        return self.name


class SeedPretreatment(models.Model):
    # CHOICES
    types_choice = (('MC', 'Mechanical'), ('CH', 'Chemical'))

    # DATABASE FIELDS

    title = models.CharField(max_length=255)
    types = models.CharField(
        max_length=255, choices=types_choice, default='MC')
    process = RichTextUploadingField(_('description'), blank=True)

    # FUNCTIONS

    class Meta:
        verbose_name = 'Seed Pre-Treatment'
        verbose_name_plural = 'Seed Pre-Treatments'

    def __str__(self):
        return '{} <{}>'.format(self.title, self.types)

    def get_absolute_url(self):
        pass


class SeedProduct(models.Model):
    folder = 'store'
    # CHOICES
    category_choice = (('FOR', 'Forestry'), ('AGR', 'Agroforestry'))
    # DATABASE FIELDS
    # BASIC INFO
    scientific_name = models.CharField(_('scientific name'), max_length=255)
    common_name = models.CharField(
        _('common name'), max_length=255, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

    # UNIQUE LINK
    slug = AutoSlugField(
        _('slug'), populate_from='scientific_name', unique=True)
    # PROFILE
    image1 = models.ImageField(_('image1'), blank=True, null=True,
                               upload_to=photo_path, default="default/product_image1.jpg")
    image2 = models.ImageField(_('image2'), blank=True, null=True,
                               upload_to=photo_path, default="default/product_image2.jpg")
    plantation_districts = models.ManyToManyField(
        District, verbose_name='Plantation districts', blank=True)

    # CART DETAILS
    price = models.IntegerField(_('price'))
    discount_price = models.FloatField(_('discount'), blank=True, null=True)
    available = models.BooleanField(default=True)
    category = models.CharField(
        max_length=3, choices=category_choice, help_text='Choose one')
    recommended = models.BooleanField(default=False)

    # ADDITIONAL INFO CARD
    seeds_kg = models.IntegerField(_('Seeds per Kilogram'), blank=True)
    seed_type = models.ForeignKey(
        TypesOfSeed, on_delete=models.SET_NULL, null=True, blank=True)
    germination_rate = models.FloatField(verbose_name='Germination Rate')
    seed_source = models.CharField(
        max_length=255, verbose_name='Seed source', blank=True)
    short_note = models.TextField(
        _('Short description'), blank=True, null=True)
    pre_treatment = models.ForeignKey(
        SeedPretreatment, on_delete=models.SET_NULL, null=True, blank=True)

    image1_thumb = ImageSpecField(source='image1', processors=[ResizeToFill(200, 100)],
                                  format='JPEG',
                                  options={'quality': 120})
    image2_thumb = ImageSpecField(source='image2', processors=[
                                  ResizeToFill(100, 200)], format='JPEG', options={'quality': 100})

    related_post = models.ForeignKey(
        BlogPost, null=True, blank=True, on_delete=models.SET_NULL)

    # FUNCTIONS

    class Meta:
        verbose_name = 'Seed Product'
        verbose_name_plural = 'Seed Products'
        ordering = ['created_on']

    def __str__(self):
        return self.scientific_name

    def get_absolute_url(self):
        return reverse('store:product', kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse('store:add-to-cart', kwargs={'slug': self.slug})

    def remove_to_cart_url(self):
        return reverse('store:remove-from-cart', kwargs={'slug': self.slug})

    def generate_card_url(self):
        return reverse('store:generate-card', kwargs={'slug': self.slug})

    def get_discount_percent(self):
        if self.discount_price:
            discount = (self.price - self.discount_price) * 100 / self.price
            return int(discount)
        return 0

    def download_pdf_url(self):
        return reverse('store:download-pdf', kwargs={'slug': self.slug})

    def edit_url(self):
        return reverse('store:edit_product', kwargs={'pk': self.id})

    def delete_url(self):
        return reverse('store:delete_product', kwargs={'pk': self.id})


class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(SeedProduct, on_delete=models.CASCADE)
    quantity = models.DecimalField(default=1, max_digits=2, decimal_places=1)

    def __str__(self):
        return f'{self.quantity} of {self.item.scientific_name}'

    def get_total_item_price(self):
        if self.item.discount_price:
            return self.quantity * self.item.discount_price
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        total = 0
        if self.item.discount_price:
            total = float(self.quantity) * self.item.discount_price
            return total
        return total

    def get_amount_saved(self):
        saved = 0
        if self.item.discount_price:
            saved = (self.item.price - self.item.discount_price) * \
                self.quantity
            return saved
        return saved

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

    def get_total_seedlings(self):
        total = 0
        if self.item.germination_rate and self.item.seeds_kg:
            number = int(self.item.germination_rate) * \
                int(self.item.seeds_kg) / 100
            total = number * float(self.quantity)
            return total
        return total


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.email

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total

    def get_total_amount_saved(self):
        amount = 0
        for order_item in self.items.all():
            amount += order_item.get_amount_saved()
            return amount
        return amount

    def subtotal(self):
        return self.get_total() + self.get_total_amount_saved()

    def order_detail_url(self):

store/forms.py
from django import forms
from django.forms import SelectMultiple, Textarea
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from .models import SeedProduct

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('M', 'MoMo Pay')
)


class CheckoutForm(forms.Form):
    # SHIPPING ADDRESS
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    shipping_street_address = forms.CharField(required=False)
    shipping_city = forms.CharField(required=False)
    shipping_district = forms.CharField(required=False)
    mobile_number = forms.CharField(max_length=100, required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False, widget=CountrySelectWidget(attrs={
            'class': 'custom-select my-1 width-90', }))
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    same_as_billing = forms.BooleanField(required=False)

    # BILLING ADDRESS
    billing_city = forms.CharField(required=False)
    billing_district = forms.CharField(required=False)
    billing_street_address = forms.CharField(max_length=100, required=False)
    email = forms.EmailField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    # PAYMENT OPTION
    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    email = forms.EmailField()


class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)


class AddProductForm(forms.ModelForm):
    class Meta:
        model = SeedProduct
        fields = ('__all__')
        widgets = {
            'short_note': Textarea(attrs={'rows': 3, 'cols': 60, 'class': 'form-control'}),
            'plantation_districts': SelectMultiple(attrs={'class': 'selectpicker form-control', 'data-style': "btn-info", 'data-size': "5"})
        }

templates/store/card.html
{% extends 'layout/base.html' %}
{% load static %}
{% load humanize %}

{% block site_name %}
{{ item.scientific_name}}
{% endblock site_name %}


{% block title %}
<link rel="stylesheet" href="{% static 'css/card.css' %}" class="css">
{% endblock title %}


{% block content %}
<div class="container">
    <div class="page-card">
        <div class="row">
            <div class="card-header">
                <div class="head-logo">
                    <h1 class="logo-text"><span>Igiti</span>&nbsp;Corp</h1>
                    <h5 class="address">Rulindo, Rwanda</h5>
                    <h5 class="date"> {% now "jS F Y H:i" %}</h5>
                </div>
                <div class="download">
                    <a href="{{ item.download_pdf_url}}" class="btn btn-default" target="_blank">Download as PDF</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="body-content">
                <div class="title name">
                    <h1 class="name-title">{{ item.scientific_name}}</h1>
                </div>

                {% if item.common_name %}

                <p>Also known as <strong>{{ item.common_name}}</strong> </p>
                {% endif %}
                <h3 class="title-content">Description</h3>

                <p>{{item.short_note}}</p>
                <h3 class="title-content">Management and Properties</h3>
                <ul>
                    <li><i class="text-success fa fa-check-square"></i>&nbsp;<span class="desc-title">Seeds per
                            Kilogram</span>:&nbsp;{{item.seeds_kg|intcomma}} seeds</li>
                    <li><i class="text-success fa fa-check-square"></i>&nbsp;<span class="desc-title">Germination
                            rate</span>:&nbsp;{{item.germination_rate}} %</li>

                    {% if item.seed_source %}
                    <li><i class="text-success fa fa-check-square"></i>&nbsp;<span class="desc-title">Seed
                            source</span>:&nbsp;{{item.seed_source}}</li>
                    {% endif %}
                </ul>
                <p></p>
                <h3 class="title-content">Plantation districts</h3>
                <table class="table table-bordered districts">
                    <thead>
                        <tr>
                            <th>
                                District
                            </th>
                            <th>
                                Ecological Zone
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for district in item.plantation_districts.all %}

                        <tr>
                            <td>
                                {{district.name}}
                            </td>
                            <td>
                                {{district.get_ecelogical_zone_display}}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                    
                <h3 class="title-content">Storage Guide</h3>

                {% if item.seed_type %}
                <p>This storage guide is pureley bsed on the seed type of <strong>{{ item.scientific_name}}</strong>
                    which is <strong>{{item.seed_type.get_name_display}}</strong></p>
                <p>
                <ul>
                    <li><i class="fa fa-check-double"></i>&nbsp;<span class="desc-title">Storage
                            type:&nbsp;</span>{{item.seed_type.get_storage_type_display}}</li>
                    <li><i class="fa fa-check-double"></i>&nbsp;<span class="desc-title">Max-storage
                            years:&nbsp;</span>{{item.seed_type.max_years}} years</li>
                    <li><i class="fa fa-check-double"></i>&nbsp;<span class="desc-title">Min-storage
                            years:&nbsp;</span>{{item.seed_type.min_years}} years</li>
                    <li><i class="fa fa-check-double"></i>&nbsp;<span class="desc-title">Max-storage
                            moisture:&nbsp;</span>{{item.seed_type.max_moisture}}&#8451;</li>
                    <li><i class="fa fa-check-double"></i>&nbsp;<span class="desc-title">Min-storage
                            moisture:&nbsp;</span>{{item.seed_type.min_moisture}}&#8451;</li>
                </ul>
                </p>
                {{ item.seed_type.overview|safe}}
                {% else %}
                <p class="font-weight-bold">Not available as of Today {% now 'F d Y' %}</p>
                {% endif %}
                <h3 class="title-content">Seed pre-treatment</h3>

                {% if item.pre_treatment %}

                <p class="treatment font-weight-bold">{{item.pre_treatment.title}}</p>
                <p class="process">
                    {{item.pre_treatment.process|safe}}
                </p>

                {% else %}
                <p>Pre-treatment not determined or it doesn't need one</p>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="foot-close">
                <div class="top">
                    &copy;Igiti Corp-{% now "M Y" %} | Powered by Feyton Inc
                </div>
                <div class="bottom">
                    <div class="mailing">
                        <ul>
                            <li><i class="fas fa-envelope"></i>&nbsp;info@igiti.co.rw</li>
                        </ul>

                    </div>
                    <div class="contact">
                        <ul>

                            <li><i class="fas fa-phone"></i>&nbsp;+25078 724 147</li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block footer_content %}

{% endblock footer_content %}


{% block extra_java %}
{% endblock extra_java %}

templates/store/order_summary.html
{% extends 'layout/base.html' %}
{% load static %}
{% load humanize %}

{% block extra_style %}
<link rel="stylesheet" href="{% static 'css/cart.css' %}" class="css">
{% endblock extra_style %}

<!-- PAGE STYLE -->
{% block site_name %}
Cart
{% endblock site_name %}

{% block content %}
<main class="page">
    <section class="shopping-cart dark">
        <div class="container">

            <div class="block-heading">
                <h2>Shopping Cart</h2>
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-md-12 col-lg-8">
                        <div class="items">

                            <!-- PRODUCT -->
                            {% for order_item in object.items.all%}

                            <div class="product">
                                <div class="row">

                                    <div class="col-md-12">
                                        <div class="info">
                                            <div class="row">
                                                <div class="col-md-4 product-name">

                                                    <h1 class="title">{{order_item.item.scientific_name}}</h1>
                                                    <div class="product-info">

                                                        {% if order_item.item.seeds_kg %}
                                                        <div>Seeds/Kg: <span
                                                                class="value">{{ order_item.item.seeds_kg|intcomma}}</span>
                                                        </div>
                                                        {% endif %}

                                                        {% if order_item.item.germination_rate %}
                                                        <div>Germination rate: <span
                                                                class="value">{{ order_item.item.germination_rate}}%</span>
                                                        </div>
                                                        {% endif %}

                                                        {% if order_item.get_total_seedlings %}
                                                        <div>Total Seedlings: <span
                                                                class="value">{{ order_item.get_total_seedlings|intcomma}}</span>
                                                        </div>

                                                        {% endif %}





                                                    </div>

                                                </div>
                                                <div class="col-md-3 quantity">
                                                    <h1 class="title">Quantity(Kg)</h1>
                                                    <div class="product-info quantity">
                                                        <div class="quantity buttons_added" data-children-count="1"><a
                                                                href="{% url 'store:remove-single-item-from-cart' order_item.item.slug%}"
                                                                class="minus">-</a>
                                                            <input type="text" pattern="[0-9]"
                                                                class="input-text qty text item-quantity" step="0.5"
                                                                min="0" max="10" name="quantity"
                                                                value="{{order_item.quantity}}" title="Qty" size="4"
                                                                inputmode="numeric" data-pk="{{order_item.pk}}">
                                                            <a href="{% url 'store:add-to-cart' order_item.item.slug%}"
                                                                class="plus">+</a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-3 price">
                                                    <h1 class="title">Price (Rwf)</h1>
                                                    <div class="product-info price">
                                                        <div>

                                                            {% if order_item.item.discount_price %}
                                                            <span
                                                                class="discount"><del>{{order_item.item.price|intcomma}}</del></span>&nbsp;{{order_item.item.discount_price}}

                                                            {% else %}

                                                            {{order_item.item.price|intcomma}}
                                                            {% endif%}
                                                        </div>

                                                    </div>

                                                </div>
                                                <div class="col-md-2 action">
                                                    <h1 class="title">Action</h1>
                                                    <div class="product-info">
                                                        <a
                                                            href="{% url 'store:remove-from-cart' order_item.item.slug%}"><i
                                                                class="fa fa-trash"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                </div>
                            </div>



                            {% empty %}

                            <div class="product">
                                <div class="row">

                                    <div class="col-md-12 empty">
                                        <h1 class="empty-title">Your Cart is empty.</h1>
                                        <a href="{% url 'store:store' %}" class="btn">Continue Shopping</a>
                                    </div>
                                </div>


                            </div>


                            <!-- //PRODUCT -->
                            {% endfor%}
                        </div>
                    </div>



                    <!-- //Product -->

                    <!-- SECTION -->
                    <div class="col-md-12 col-lg-4">
                        <div class="summary" id="order-summary">
                            {% include "snippets/order-summary.html" with order=object%}
                        </div>
                    </div>
                    <!-- //SECTION -->
                </div>
    </section>
</main>

{% endblock content %}
{% block extra_java %}
<script>
    $('.item-quantity').change(function (e) {
        var pk = $(this).data('pk');
        var quantity = $(this).val();
        if (quantity >= 9.1) {
            alert("Quantity can not exceed 9");
            $(this).val(9);
            var q = 9

        } else if (quantity <= 0) {
            alert("Quantity can't be 0'");
            $(this).val(1);

        }
        $.ajax({
            url: "{% url 'store:update-item-cart-quantity' %}",
            method: 'GET',
            data: { 'pk': pk, 'q': quantity },
            success: function (data) {
                $.notify({
                    title: 'Quantity updated',
                    message: 'Quantity has been changed successfully'
                }, {
                    type: 'success',
                    delay: 3000
                })
            }
        })
    })
</script>

{% endblock extra_java %}




{% block footer_content %}

{% endblock footer_content %}