corp/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import RedirectView
from index.views import home, species
from user.views import Dashboard
from django.urls import re_path

admin.autodiscover()

urlpatterns = [

    path("ads.txt", RedirectView.as_view(
        url=staticfiles_storage.url("ads.txt")),),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('species/', species),
    path('user/', include('user.urls')),
    path('ckeditor', include(
        'ckeditor_uploader.urls')),
    path('forestry/', include(('forestry.urls',
                               'forestry'), namespace='forestry')),
    path('accounts/', include('allauth.urls')),
    path(
        'store/', include(('store.urls', 'store'), namespace='store')),
    path('dashboard/', Dashboard.as_view(),
         name='profile'),
    path('hitcount/', include(('hitcount.urls',
                               'hitcount'), namespace='hitcount')),
    path('dashboad/', include(('dashboard.urls',
                               'dashboard'), namespace='dashboard')),

)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('remove_task/<int:pk>/<action>/',
         views.remove_task, name='remove_task'),
    path('remove_worker/<pk>/', views.delete_worker, name='remove-worker'),
    path('task/<pk>/', views.complete_task, name='complete_task'),
]

dashboard/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class NurseryManager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=50, blank=False, null=True)
    telephone = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return '%s - %s' % (self.user.get_full_name(), self.location)


class Species(models.Model):
    scientific_name = models.CharField(
        blank=False, unique=True, max_length=255)
    seeds_kg = models.IntegerField(blank=True)


class Nursery(models.Model):
    # Choices

    # DATABASE

    manager = models.ForeignKey(NurseryManager, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=False)
    location = models.CharField(max_length=100, blank=True, null=True)
    species = models.ManyToManyField(Species)


class SowingBed(models.Model):
    nursery = models.ForeignKey(Nursery, on_delete=models.CASCADE)
    size = models.CharField(max_length=255, blank=True, null=True)
    specie = models.ManyToManyField(Species)
    sowing_date = models.DateTimeField(auto_now=False, blank=True, null=True)


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    action = models.CharField(max_length=255, blank=False, null=False)
    date_completed = models.DateTimeField(
        blank=True, null=True, auto_now_add=False)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name

    def complete_url(self):
        return reverse('dashboard:complete_task', kwargs={'pk': self.id})


class Workers(models.Model):
    # CHOICES
    # DATABASE
    account_number = models.CharField(max_length=20, blank=True)
    full_name = models.CharField(max_length=255, )
    job = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    salary = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.full_name

    def pay_url(self):
        return reverse('dashboard:pay_worker', kwargs={'pk': self.id})

    def delete_url(self):
        return reverse('dashboard:remove-worker', kwargs={'pk': self.id})

dashboard/forms.py
from django import forms
from django.forms import ModelForm

from .models import Nursery, Task, Workers


class AddTaskForm(ModelForm):
    class Meta:
        model = Task
        exclude = ['user']


class NurseryForm(ModelForm):
    class Meta:
        model = Nursery
        fields = '__all__'


class AddWorker(ModelForm):
    class Meta:
        model = Workers
        fields = '__all__'

dashboard/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth import get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.db.models.functions import Trunc
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from store.models import SeedProduct

from .models import Task, Workers

User = get_user_model()


@login_required
def remove_task(request, pk, action):
    task = get_object_or_404(Task, pk=pk)
    task_qs = Task.objects.filter(user=request.user, status=False)

    if task_qs.exists():
        task = task_qs[0]
        ref = task.id
        if action == "delete":
            task.delete()
            messages.info(request, 'Task deleted')
            return JsonResponse({'message': "Task deleted", "id": ref})
        elif action == "completed":
            task.status = True
            task.date_completed = timezone.now()
            task.save()
            return JsonResponse({'message': "Task has been completed", "id": ref})
        else:
            return render(request, "dashboard/includes/forms.html")

    else:
        return JsonResponse({'message': "You don't have a task"})


@login_required
def complete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task_qs = Task.objects.filter(user=request.user, status=False)

    if task_qs.exists():
        task = task_qs[0]
        task.status = True
        task.date_completed = datetime.now()
        task.save()
        messages.info(request, 'Task completed')
        return redirect('profile')
    else:
        messages.info(request, "Not found")
        return redirect('profile')


@login_required
def delete_worker(request, pk):
    worker = Workers.objects.get(id=pk)
    name = worker.full_name

    worker.delete()
    messages.warning(request, '{} - Has been removed'.format(name))
    return redirect('notification')

templates/dashboard/index.html
{% extends 'dashboard/layouts/base.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}


<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'assets/demo/form.css' %}" class="css">
{% endblock stylesheets %}


{% block content %}

<!-- End Navbar -->

<div class="panel-header panel-header-sm">
  <div class="header ml-5">
    <h3 class="title mt-n4">Welcome <span class="text-success">{{user.first_name}}</span></h3>
  </div>
</div>
<div class="content">


  <!-- CARD TASK -->
  <div class="row">
    <div class="col-md-6">
      <div class="card  card-tasks">
        <div class="card-header ">
          <h5 class="card-category">Become more productive</h5>
          <h4 class="card-title">Here are your tasks</h4>
        </div>
        <div class="card-body ">
          <div class="table-full-width table-responsive">
            <table class="table">
              <tbody>
                <!-- TASK -->

                {% for task in tasks %}

                <tr id="task{{task.id}}">
                  <td>
                    <div class="form-check">
                      <label class="form-check-label">
                        <input class="form-check-input complete-task" type="checkbox"
                          data-url="{% url 'dashboard:remove_task' pk=task.pk action='completed' %}">
                        <span class="form-check-sign"></span>
                      </label>
                    </div>
                  </td>
                  <td class="text-left">{{task.action|escape}}</td>
                  <td class="td-actions text-right">
                    <button class="btn btn-danger btn-round btn-icon btn-icon-mini btn-neutral delete-task"
                      data-original-title="Remove"
                      data-url="{% url 'dashboard:remove_task' pk=task.pk action='delete' %}">
                      <i class="now-ui-icons ui-1_simple-remove"></i></button>
                  </td>
                </tr>
                {% endfor %}

                <!-- // TASK -->

              </tbody>
            </table>



          </div>
          <hr>
          <button data-toggle="modal" data-target="#exampleModal" class="btn btn-warning">Add Task</button>
        </div>
      </div>
    </div>
    <!-- // TASK  CARD -->
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h5 class="card-category">All Persons List</h5>
          <h4 class="card-title"> Employees Stats</h4>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <thead class=" text-primary">
                <th>
                  Name
                </th>
                <th>
                  Country
                </th>
                <th>
                  City
                </th>
                <th class="text-right">
                  Salary
                </th>
                <th class="text-right">
                  Action
                </th>
              </thead>
              <tbody>
                <!-- WORKER -->

                {% for worker in workers %}



                <tr>
                  <td>
                    {{worker.full_name}}
                  </td>
                  <td>
                    {{worker.country}}
                  </td>
                  <td>
                    {{ worker.city}}
                  </td>
                  <td class="text-right">
                    {{worker.salary|intcomma}}&nbsp;Rwf
                  </td>
                  <td class="text-right">
                    <a type="button" rel="tooltip" title=""
                      class="btn btn-info btn-round btn-icon btn-icon-mini btn-neutral" data-original-title="Edit Task">
                      <i class="now-ui-icons ui-2_settings-90"></i>
                    </a>
                    <a href="{{ worker.delete_url}}" class="btn btn-danger btn-round btn-icon btn-icon-mini btn-neutral"
                      data-original-title="Remove">
                      <i class="now-ui-icons ui-1_simple-remove"></i>
                    </a>
                  </td>
                </tr>
                {% endfor %}
                <!-- //WORKER -->
              </tbody>
            </table>
            <hr>
            <button class="btn btn-primary" data-toggle="modal" data-target="#addWorker" id="add-worker">Add New
              worker</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- FORMS -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Task</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" action=".">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="message-text" class="col-form-label">Action:</label>
                <textarea class="form-control" id="message-text" name="action" rows="2"></textarea>
              </div>
            </div>
          </div>

          <input type="submit" value="Add Task" class="btn btn-success">
        </form>
      </div>
    </div>
  </div>
</div>


<!-- ADD WORKER FORM -->
<div class="modal fade" aria-hidden="true" id="addWorker" tabindex="-1" role="dialog" aria-labelledby="addWorker">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addWorkerLabel">New Worker</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" action="." class="md-form">
          {% csrf_token %}
          {% include 'dashboard/includes/forms.html' with form=add_worker_form %}

          <input type="submit" value="Add Worker" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</div>
<!-- // FORMS -->

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script src="{% static 'js/dashboard.js' %}"></script>

<script>
  $("input[type=file]").change(function () {
    let filePath = $(this)[0].files[0].name;
    $(this).prev('label').text(filePath);
  })
  var $select = $("form select");
  $select.each(function () {
    $(this).addClass('custom-select w-90')
  });
  var $text = $("form :input[type='text']");
  $text.each(function () {
    $(this).addClass("form-control");
  });
  var $list = $("form :input[type='number']");
  $list.each(function () {
    $(this).addClass("form-control");
  });
  $(".complete-task").change(function (e) {
    if (this.checked) {
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonClass: 'btn btn-success',
        cancelButtonClass: 'btn btn-danger',
        confirmButtonText: 'Yes, the task is complete',
        buttonsStyling: false
      }).then((result) => {
        if (result.value) {
          var endpoint = $(this).data('url')
          $.ajax({
            method: 'GET',
            url: endpoint,
            success: function (data) {
              Swal.fire({
                title: 'Completed!',
                text: 'Task has been completed',
                type: 'success',
                confirmButtonClass: 'btn btn-success',
                buttonsStyling: false,
                timer: 2000,
              });
              console.log(data)

              $("#task" + data.id).hide(1000)

            },
            error: function (error_data) {
              console.log(error_data);

            }
          });

        } else {
          $(this).prop('checked', !$(this).prop('checked'));
          Swal.fire({
            title: 'Cancelled',
            text: 'Task remained intact',
            timer: 2000
          })
        }
      });

    } else {
    };
    $(".delete-task").click(function (e) {
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonClass: 'btn btn-success',
        cancelButtonClass: 'btn btn-danger',
        confirmButtonText: 'Yes, delete it!',
        buttonsStyling: false
      }).then((result) => {
        if (result.value) {
          var endpoint = $(this).data('url')
          $.ajax({
            method: 'GET',
            url: endpoint,
            success: function (data) {
              Swal.fire({
                title: 'Completed!',
                text: 'Task has been deleted',
                type: 'success',
                confirmButtonClass: 'btn btn-success',
                buttonsStyling: false,
                timer: 2000,
              });
              console.log(data)

              $("#task" + data.id).hide(1000)

            },
            error: function (error_data) {
              console.log(error_data);

            }
          });

        } else {
          e.preventDefault();
          Swal.fire({
            title: 'Cancelled',
            text: 'Task remained intact',
            timer: 2000
          })
        }
      });

    })
  })
</script>

{% endblock javascripts %}